version: '3.8'
services:
  postgres:
    container_name: postgres
    command: ["postgres", "-c", "log_statement=all"]
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: imbue
      POSTGRES_PASSWORD: imbue
      PGDATA: /var/lib/postgresql/pgdata/
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
